# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'facemate-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for facemate-test
  pod 'JTAppleCalendar', '~> 7.0'

  target 'facemate-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'facemate-testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
