# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fmtest2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fmtest2
  pod 'CVCalendar', '~> 1.5'

  target 'fmtest2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fmtest2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
